### ISSUE TITLE
Regarding Multivalue Answer Routing Policy and record - Alias or Non Alias

### ISSUE THREAD

**Issue by himanshughildiyal** [awsdocs/amazon-route53-docs#14]
Hi,

I've a question regarding multianswer routing policy as per the document below 
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-values-alias.html#rrsets-values-alias-alias

I wanted clarification if at the zone apex , can we create a Non Alias record , if routing policy 
is MultiAnswer ?  

If we select Non Alias  , it does create a record for us but in documentation above
you have mentioned that ONLY ALIAS records can be created at zone apex / naked domain.

Note: This is not for  record "type" but for the DNS record  itself.

Please clarify .

Thanks
Himanshu

**Comment by skralik** [comment]
Hi,

We don't currently support creating multivalue answer alias records. For settings for multivalue answer records, see "Values for Multivalue Answer Records" in the _Route 53 Developer Guide_:

You can create any record except a CNAME record at the zone apex, such as example.com. An alias record provides a workaround for that limitation of DNS. For more information about the difference between standard CNAME records and Route 53 alias records, see "Choosing Between Alias and Non-Alias Records":

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-choosing-alias-non-alias.html

Scott
