### ISSUE TITLE
domain-delete docs suggest domain registrations can be refunded

### ISSUE THREAD

**Issue by sudoforge** [awsdocs/amazon-route53-docs#2]
The documentation for `domain-delete` contains the following language:

> **Important**
> If you delete a domain name registration before the registration was scheduled to expire, we will not refund the registration fee.

This suggests that domain registrations can be refunded. I have, however, confirmed with the AWS Support Team that domain registrations are one of the few Route53-related transactions that cannot be refunded.

**Comment by skralik** [comment]
Thanks for the additional information. As you can imagine, several folks review any text related to fees. Having looked over this again, we’ve decided to keep the current wording. But thank you again for bringing this to our attention and prompting us to take a look.
