### ISSUE TITLE
Document Health Checker behavior

### ISSUE THREAD

**Issue by pseidel-kcf** [awsdocs/amazon-route53-docs#20]
It would be useful to have some details about the nuances of the Health Checker documented.

After enabling compression on our application we had to determine through trial and error that a Health Check with SearchString does not support Brotli encoding but does support Gzip. The only documentation I saw was that the string needed to be in the first 5120 bytes of the response and that headers needed to be RFC compliant. AWS Support tried to be helpful but it seems they were armed with the same documentation I was.

In this particular instance it would have helped if I had known:
- The User-Agent used by Route53 health checks. After googling this I see that it has changed at least once in the past. Knowing the User-Agent I can add some checks to only return Gzip for Route53 while using more efficient Brotli for modern browsers and clients. The current User-Agent looks like `Amazon-Route53-Health-Check-Service (ref $GUID; report http://amzn.to/1vsZADi`
- What the actual accepted encodings are. My application was receiving `Accept-Encoding: *`, which is fine for simply checking HTTP response status, but perhaps something like `Accept-Encoding: gzip, identity` would be more appropriate when StringSearch is enabled.

I'm sure there are other details about the request and response which could be useful to include.

**Comment by joshbean** [comment]
Hi @pseidel-kcf –

Firstly, I'm sorry for the terrible delay responding to this! We endeavor to respond much more quickly than what you're seeing now.

As to your request, thanks for taking the time to provide the details of what you're looking for. This makes sense, and would be a helpful addition to the Route 53 documentation. I don't have a timeline for you of when we might be able to provide this, but I will leave this issue open in the meantime.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
