### ISSUE TITLE
"External resource such as a database server"

### ISSUE THREAD

**Issue by wiredin** [awsdocs/amazon-route53-docs#25]
The page for configuring health checks for private zones seems to have a very peculiar recommendation:
 
"You can configure a health checker to check the health of an external resource that the instance relies on, such as a database server."

You may want to choose a different example, this one could confuse less security focused people and encourage them to do something like expose a database to the internet so that it can be used for a DNS health check.....

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover-private-hosted-zones.html

**Comment by Sirkkuw** [comment]
@wiredin Thank you for that suggestion. I am working on removing that bullet.
