### ISSUE TITLE
bucket name must match domain name

### ISSUE THREAD

**Issue by Ronser** [awsdocs/amazon-route53-docs#30]
Hi

I followed the instructions for creating a static site with a custom domain in an S3 bucket. However, I found some steps confusing and it took some troubleshooting. In particular, **step 12** in this topic: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/getting-started-s3.html#getting-started-create-alias

Here are some issues that might benefit some further attention:

- "The bucket name should match the name that appears in the Name box."
I don't see any "Name" box in the Define simple record dialog. I was confused about what Name box you are referring to here.

- "In the Choose S3 bucket list,..."
I didn't see any Choose S3 bucket list. There is a text field with the words "Enter S3 endpoint" as placeholder text, perhaps this is the text that should be referenced in the step? I feel like the page was updated but the instructions might be out of date.

- Finally, I missed this note that indicates that your bucket name must be the same as your record name for the two to resolve:
"The bucket name is the same as the name of the record that you're creating."
I feel like this should be noted when you are creating the bucket. For example: "Note: The name of your bucket must match the name of the domain you create in step one."
I created a domain, let's call it my-sample-domain.com. Then I created a bucket and called it: myWebsiteFiles. But when I went to route DNS traffic to the bucket, I found that the bucket has to have the same name as the record. The record will have the same name as the domain. And so I had to delete the bucket and create a new bucket called my-sample-domain.com. Then it worked. 

I am happy to fork and create a pull request to work on suggested changes. Please let me know if you can reproduce this or I misunderstood your steps.

Thanks

Ronan

**Comment by Sirkkuw** [comment]
Hi @Ronser - I will take a look and see if I can improve the steps. Sometimes the UI changes and I might miss those changes. Thank you for taking the time to comment!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
