### ISSUE TITLE
Unable to select different region for cloudfront distribution

### ISSUE THREAD

**Issue by Antonyrahul** [awsdocs/amazon-route53-docs#37]
I am trying to route traffic to a cloudfront distribution and i was following the document. As stated i selected the Alias to cloudfront distribution from the dropdown but from there i am not able to selcet my region as N.Virginia is hardcoded in the region dropdown. Is there something i am missing
![aws_cdn](https://user-images.githubusercontent.com/24284297/182786086-31500a9b-cdad-4b71-b4b2-8f1c1ceac9f9.PNG)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
